# Generated by Django 3.1.6 on 2021-10-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_profile_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_verified',
        ),
    ]
