# Generated by Django 3.2.4 on 2021-10-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeuser',
            name='otp',
            field=models.CharField(default=1, max_length=4, unique=True),
            preserve_default=False,
        ),
    ]
